version: '3'

services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: